### ISSUE TITLE
Provide a refresh method

### ISSUE THREAD

**Issue by hirbod** [kleimaj/multi-select#1]
Hi, 

I am loading parts of my content async. Your library does not have any global trigger / reinit function.
Could you provide one? Maybe exposed to the window namespace?

`window.multiSelect.refresh()`

It should only detect newly, uninitialized elements. You might just want to add a data-multiselect-initialized="true" and do a querySelect where this data-tag is false and retrigger your code?

I would also suggest you don't bind it fixed to "multi", provide a class constructor to pass a selector to it.

Thanks for your effort.

**Comment by kleimaj** [comment]
Hey Hirbod,

Thanks for opening an issue. I have gone ahead and implemented a refresh method. For You can call `multiSelect()` or `window.multiSelect.refresh()`. Like you suggested, it will only initialize newly detected elements, and not alter the state of existing ones.

I have taken into consideration using a class constructor. And I believe you are correct, this would work best and keep my package scalable. I will be implementing that this weekend for the next iteration of the multiSelect.js release. 

Thanks again for your input!

Jacob

**Comment by hirbod** [comment]
Hi @kleimaj thanks for your quick response and work.
I thought a bit deeper about it, and I think it should also be possible to reinit already initialized selects. The reason what I think about for example is async options) which might be added dynamically. 

I've seen libs they have refresh() and forceRefresh(), while the forceMethod will also reinit already initalized ones.

Would be great if your library could also export as module/umd/amd to be importable/requireble using webpack/babelify etc.

Thanks for your effort.

**Comment by kleimaj** [comment]
Thanks @Hirbod for your ideas, I'm going ahead and closing this issue since it only pertains to the refresh method. I will work on making this package module friendly for future use.
